language: ruby
rvm:
- 2.5.5
before_script: 
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: ca5ffc8a-df84-4d17-b392-0379d2a9b547
  app: utbm-web-project
  on:
    repo: vareversat/UTBM-Web-Project
  skip_cleanup: true
  run: "rails db:migrate"
