language: ruby
services: postgresql
rvm:
- 2.5.3
before_script:  
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: 08454402-33a8-474c-9f55-acf568e91e49
  app: utbm-web-project
  on:
    repo: vareversat/UTBM-Web-Project
  skip_cleanup: true
  run: "rails db:migrate"
