version: '3'
services:
  db:
    networks: 
      - net_app
    image: postgres:latest
    restart: always
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    container_name: postgresql
  ruby:
    networks:  
      - net_app
    build: .
    depends_on: 
      - db
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && 
            rake db:drop && 
            rake db:create && 
            rake db:migrate && 
            ruby ./scripts/init_db_products.rb &&
            bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    container_name: ruby
networks:
  net_app:
      driver: bridge
