version: '3'
services:
  db:
    image: postgres
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    container_name: postgresql
  frontend:
    build: ../UTBM-Web-Project-frontend/
    volumes:
      - ../UTBM-Web-Project-frontend/:/myapp
    ports:
      - "4200:4200"
    container_name: angular
  ruby:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: ruby