default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: <%= ENV["DB_DEV"] %>

test:
  <<: *default
  database: <%= ENV["DB_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DB_PROD"] %>